### PR TITLE
Use "safe" discretization via midpoints

### LINKED ISSUE #74: Discretization may lead to numerical instabilities
Under certain circumstances, the way that analytical controls are currently discretized onto the time grid may lead to numerical instabilities. This happens in particular for flattop update shapes with a very quick switch-on. In this case, the internal sampling on the intervals of the time grid that is being used inside `krotov` leads to a zig-zag around the "flat" values 1.0 after the switch-on.

See the [attached notebook "Numerical instabilities in Krotov's method due to pulse discretization"](https://nbviewer.jupyter.org/gist/goerz/14b8fdc868ed4fb3419ea2fe3d183310) for details.

The solution (as described in the notebook) is to sample analytical controls on the time grid interval midpoints first, and then average those exact values onto the time grid points. Since averaging (as opposed to the inverse "un-averaging") is numerically safe, we can guarantee numerically stable pulses this way.

In practice, for the current `krotov 1.1.0`, any attempt to use an update shape that runs into this problem to a significant degree would trigger a `ValueError` due to the update shape going over its maximum allowed value of 1.0 after conversion to the midpoints. @zachmanson (U Windsor) reported such an error via private communication.

### PR DESCRIPTION
**Pull request by goerz**
Closes #74

### CODE REVIEW

**Comment by goerz** [comment]
@zachmanson You should now be getting notifications on this

**Comment by goerz** [comment]
@zachmanson This is now ready. Let me know if you want to review/test this. Otherwise, I'll merge this branch and put out a new release for `krotov` soon.

**Comment by zachmanson** [comment]
I will test this out tomorrow and let you know what I think

**Comment by goerz** [comment]
Thanks! I added you as a collaborator with the ability to review (if I understood the settings on Github correctly).

**Pull request merged**
